ARG PYTHON_VERSION=3.12
ARG BASE_OS=alpine

ARG PYTHONDONTWRITEBYTECODE=1
ARG PYTHONBUFFERED=1

ARG VIRTUAL_ENV=/opt/venv

# Use a multi-stage build to reduce the size of the final image.
#   This example is optimized to reduce final image size rather than for
#   simplicity.
# Using a -slim image also greatly reduces image size.
# It is possible to use -alpine images instead to further reduce image size,
# but this comes with several important caveats.
#   - Alpine images use MUSL rather than GLIBC (as used in the default
#   Debian-based images).
#   - Most Python packages that require C code are tested against GLIBC, so
#   there could be subtle errors when using MUSL.
#   - These Python packages usually only provide binary wheels for GLIBC, so
#   the packages will need to be recompiled fully within the container images,
#   increasing build times.
FROM docker.io/python:${PYTHON_VERSION}-${BASE_OS} AS python_builder

# Set ENV variables that make Python more friendly to running inside a
# container.
ARG PYTHONDONTWRITEBYTECODE
ARG PYTHONBUFFERED

# Install any system dependencies required to build wheels, such as C
# compilers or system packages For example:
RUN apk add --update --no-cache curl && \
  rm -rf /var/cache/apk/*

ARG VIRTUAL_ENV
ARG UV_BIN="/root/.cargo/bin"
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN ${UV_BIN}/uv venv \
        --python-preference="only-system" \
        --python=${PYTHON_VERSION} \
        ${VIRTUAL_ENV}

# Copy in project dependency specification.
ARG WORKDIR=/src
WORKDIR ${WORKDIR}

# Install the project dependencies
COPY pyproject.toml ./
RUN ${UV_BIN}/uv pip compile \
        --python-preference="only-system" \
        --python=${PYTHON_VERSION} \
        --output-file="requirements.txt" \
        --quiet \
        --all-extras \
        pyproject.toml && \
    ${UV_BIN}/uv pip install \
        --python-preference="only-system" \
        --python=${PYTHON_VERSION} \
        --quiet \
        --requirement requirements.txt && \
    rm requirements.txt

# Copy in source files.
COPY README.md COPYING hatch.toml hatch_build.py ./
COPY src src/

# Manually build/install the package.
RUN ${UV_BIN}/uv pip install \
        --python-preference="only-system" \
        --python=${PYTHON_VERSION} --no-cache \
        --quiet \
        --no-deps \
        . && \
    find ${VIRTUAL_ENV} -name '*.pyc' -type f -delete && \
    find ${VIRTUAL_ENV} -name '__pycache__' -type d -delete && \
    find ${VIRTUAL_ENV} -name '*.egg-info' -type d -delete

## Final Image
# The image used in the final image MUST match exactly to the python_builder
# image.
FROM docker.io/python:${PYTHON_VERSION}-${BASE_OS}
MAINTAINER Romain Brault <mail@romainbrault.com>

RUN apk add --update --no-cache git && \
  rm -rf /var/cache/apk/*

# For Python applications that are not installable libraries, you may need to
# copy in source files here in the final image rather than in the
# python_builder image.

# Copy and activate pre-built virtual environment.
ARG VIRTUAL_ENV
COPY --from=python_builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}
ENV PATH "${VIRTUAL_ENV}/bin:${PATH}"

# Create the user so the program doesn't run as root. This increases security
# of the container.
ENV USER user
ENV HOME /home/${USER}
RUN addgroup ${USER} && \
    adduser \
    --disabled-password \
    --gecos "" \
    --home "${HOME}" \
    --ingroup "${USER}" \
    "$USER"

# Give access to the entire home folder to the new user so that files and
# folders can be written there. Some packages such as matplotlib, want to write
# to the home folder.

USER user

# Setup application install directory.
ENV APP_HOME ${HOME}/app
RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}

ARG PYTHONDONTWRITEBYTECODE
ARG PYTHONBUFFERED
ENV PYTHONDONTWRITEBYTECODE ${PYTHONDONTWRITEBYTECODE} \
    PYTHONBUFFERED ${PYTHONBUFFERED}

ENV WHITEPRINT_HOME ${HOME}/whiteprint
RUN mkdir -p ${WHITEPRINT_HOME}
COPY template/ ${WHITEPRINT_HOME}/template/
COPY jinja_template/ ${WHITEPRINT_HOME}/jinja_template/
COPY copier.yml ${WHITEPRINT_HOME}

ENTRYPOINT ["whiteprint"]

ARG BUILD_DATE
ARG VERSION
ARG REVISION
ARG TAG

LABEL org.opencontainers.image.authors='Romain Brault <mail@romainbrault.com>' \
      org.opencontainers.image.url='https://github.com/whiteprints/whiteprint/pkgs/container/whiteprint' \
      org.opencontainers.image.documentation='https://romainbrault.github.io/whiteprint/' \
      org.opencontainers.image.source='https://github.com/whiteprints/whiteprint.git' \
      org.opencontainers.image.vendor='Romain Brault' \
      org.opencontainers.image.licenses='MIT' \
      org.opencontainers.image.version=${VERSION} \
      org.opencontainers.image.revision=${REVISION} \
      org.opencontainers.image.created=${BUILD_DATE} \
      org.opencontainers.image.title='whiteprint' \
      org.opencontainers.image.description='A cookiecutter for quick creation of Python projects.' \
      org.opencontainers.image.ref.name=${TAG} \
      org.opencontainers.image.base.name='docker.io/python:'${PYTHON_VERSION}'-'${BASE_OS}
