version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(dependency): ⬆️"
      prefix-development: "build(dev-dependency): ⬆️"
    labels:
      - "ci"
      - "github_actions"
      - "dependencies"
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci(dependency): ⬆️"
      prefix-development: "ci(dev-dependency): ⬆️"
    labels:
      - "ci"
      - "github_actions"
      - "dependencies"
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    commit-message:
      prefix: "docs(dependency): ⬆️"
      prefix-development: "docs(dev=dependency): ⬆️"
    labels:
      - "documentation"
      - "dependencies"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 99
    commit-message:
      prefix: "build(dependency): ⬆️"
      prefix-development: "build(dev-dependency): ⬆️"
    allow:
      - dependency-type: "all"
    labels:
      - "python"
      - "build"
      - "dependencies"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build(dependency): ⬆️"
      prefix-development: "build(dev-dependency): ⬆️"
    labels:
      - "container"
      - "dependencies"
