blank_issues_enabled: false
contact_links:
  - name: 🙏 Question or Problem
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://github.com/whiteprints/whiteprint/discussions/categories/q-a
  - name: 💡 New idea
    about: To suggest an idea or ask about a feature, please start with a question saying what you would like to achieve. There might be a way to do it already.
    url: https://github.com/whiteprints/whiteprint/discussions/categories/ideas
  - name: 🙌 Show and tell
    about: Show what you built with Python Whiteprint
    url: https://github.com/whiteprints/whiteprint/discussions/categories/show-and-tell
