name: Documentation

env:
  PYTHON_VERSION: "3.11"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docs:
    name: Build documentation & check links
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5.1.1
        id: setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          check-latest: true

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install Nox
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt nox
          pipx inject --pip-args=--constraint=.github/workflows/constraints.txt nox nox-poetry rich
          nox --version

      - name: Build documentation
        run: nox --force-color --session=docs-build --force-python="${{ steps.setup-python.outputs.python-path }}"

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs/_build

      - name: Check links
        run: nox --force-color --session=docs-check-links --force-python="${{ steps.setup-python.outputs.python-path }}"
