name: "Pull Request Labeler"
on:
  pull_request:
    branches: ["main"]

jobs:
  pr-triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@4.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
